sudo: required
language: go
go:
- 1.6.3
- 1.7.1
env:
  global:
    - SNAP_PLUGIN_SOURCE=/home/travis/gopath/src/github.com/Staples-Inc/snap-plugin-collector-procstat
  matrix:
    - TEST=unit
before_install:
- mkdir $GOPATH/bin
- curl https://glide.sh/get | sh
- go get github.com/smartystreets/goconvey/convey
- go get github.com/stretchr/testify
- if [ ! -d $SNAP_PLUGIN_SOURCE ]; then mkdir -p $HOME/gopath/src/github.com/staples-inc; ln -s $TRAVIS_BUILD_DIR $SNAP_PLUGIN_SOURCE; fi # CI for forks not from staples-inc
install:
- export TMPDIR=$HOME/tmp
- mkdir -p $TMPDIR
- cd $SNAP_PLUGIN_SOURCE # change dir into source
- make deps
script:
- make test  # Run test suite